name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: jupyverse-dev
        environment-file: dev-environment.yml
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge

    - name: Install jupyverse
      run: |
        pip install ./plugins/frontend
        pip install ./plugins/jupyterlab
        pip install ./plugins/login
        pip install ./plugins/auth
        pip install ./plugins/contents
        pip install ./plugins/kernels
        pip install ./plugins/terminals
        pip install ./plugins/lab
        pip install ./plugins/nbconvert
        pip install ./plugins/yjs
        pip install .[test]

    - name: Check types
      run: |
        mypy jupyverse
        mypy plugins/frontend/fps_frontend
        mypy plugins/contents/fps_contents
        mypy plugins/kernels/fps_kernels
        mypy plugins/retrolab/fps_retrolab
        mypy plugins/jupyterlab/fps_jupyterlab
        mypy plugins/lab/fps_lab
        mypy plugins/auth/fps_auth
        mypy plugins/nbconvert/fps_nbconvert
        mypy plugins/yjs/fps_yjs
        mypy plugins/terminals/fps_terminals
        mypy plugins/login/fps_login

    - name: Run tests
      run: |
        pytest ./tests -v
